name: Java CI

# From the following:
# https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events  for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows us to also run manually from the actions tab for any workflow, see
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew build
